### ISSUE TITLE
Ola's Playful Practice with "Edit profile #116"

### ISSUE THREAD

**Issue by olavea** [raae/pow-app#122]
@raae said in #116 :
The user should be able to edit/change 

- [ ] Email 
- [ ] Username
Password, is a little trickier, so let's wait with it

This will be very similar to signup/signin form. 
- [ ]  Maybe create a new variant "update". 

- [ ]  @olavea start with email.

Instead of doing lots of conditionals like `{variant === "signup" || variant === "signin" <etc>`. It could be good to do 
- [ ]  create some helper variables. For instance create
- [ ] `const showEmail = variant === "signup" || variant === "update"` and then use
- [ ]  {showEmail && <TextField <etc>}.

**Comment by raae** [comment]
I have been unclear, I do not want them all to be edited on the same screen.
One for each. Otherwise it can be very confusing.

And to answer a comment I saw, we do want a new page. But later it will be a modal (popup) on large screens and a new page on smaller screens. We are optimizing for smaller screens first.
